spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JwtAuthDB
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: qwerty
    key-store-type: JKS
    key-alias: myapp
